server:
    port: 8081
spring:
    application:
        name: login-service
eureka:
    client:
        service-url:
            defaultZone: http://192.168.10.100:8761/eureka
    instance:
        hostname: localhost
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
